### PR TITLE
adding 9anime and twitch support

### PR DESCRIPTION
**Pull request by 6lyxt**
no desc needed

### CODE REVIEW

**Comment by lolamtisch** [comment]
I see that you are still working on it. Give me a callout here when you are ready and i will take a look.

**Comment by 6lyxt** [comment]
done so far.

**Comment by 6lyxt** [comment]
is this still valid for merging?

**Comment by lolamtisch** [comment]
Sorry. I took a look.

twitch seems not to work for me at all. But that page is really difficult to implement, because of the many differente pages: live stream, home and videos. We were nearly done, but then we lost the code. I will do an implementation of twitch soon myself again. I hope that is fine with you.

9anime works. But we have a small problem i am not sure how to handle. Because MALSync already has an presence for 9anime and it has much more functionality like displaying the state(play/stop), the episode number and the time to the end of the episode. The question is, is this presence even needed as it already exist. At the other hand MALSync does a lot on top of that, which has to be deactivatet first. So i am a bit split if to add it or not. What do you think?

**Comment by 6lyxt** [comment]
im pretty confused, twitch works just fine for me. 

im fine with twitch & i would also be fine if youre not adding 9anime at all, since malsync has more functionality. could you try twitch by going over www.twitch.tv tho? it works for my friends too, they tested it.

**Comment by 6lyxt** [comment]
alright fixed twitch, didnt work because of the update on twitch

**Comment by lolamtisch** [comment]
I throw something together on the branch twitch. if you want you can test it. Should be a bit better than yours
https://github.com/lolamtisch/Discord-RPC-Pack/tree/twitch

**Comment by 6lyxt** [comment]
yeah its better

**Pull request closed without merging**
